// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Preact from "bs-preact/src/Preact.bs.js";
import * as Preact$1 from "preact";
import * as Hooks from "preact/hooks";

function reducer(state, param) {
  if (param) {
    return state - 1 | 0;
  } else {
    return state + 1 | 0;
  }
}

var make = Preact.component("Counter", (function (initial) {
        var match = Hooks.useReducer(reducer, initial, undefined);
        var dispatch = match[1];
        return Preact.div(/* [] */0, /* :: */[
                    Preact.button(/* :: */[
                          Preact.onClick((function (param) {
                                  return Curry._1(dispatch, /* Decrement */1);
                                })),
                          /* [] */0
                        ], /* :: */[
                          "-",
                          /* [] */0
                        ]),
                    /* :: */[
                      " ",
                      /* :: */[
                        match[0],
                        /* :: */[
                          " ",
                          /* :: */[
                            Preact.button(/* :: */[
                                  Preact.onClick((function (param) {
                                          return Curry._1(dispatch, /* Increment */0);
                                        })),
                                  /* [] */0
                                ], /* :: */[
                                  "+",
                                  /* [] */0
                                ]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]);
      }));

var Counter = /* module */[
  /* reducer */reducer,
  /* make */make
];

var main = Preact.div(/* [] */0, /* :: */[
      Curry._1(make, -3),
      /* :: */[
        Curry._1(make, 0),
        /* :: */[
          Curry._1(make, 3),
          /* [] */0
        ]
      ]
    ]);

var match = document.querySelector("main");

if (match == null) {
  console.error("<main> not found!");
} else {
  Preact$1.render(main, match);
}

var P = 0;

export {
  P ,
  Counter ,
  main ,
  
}
/* make Not a pure module */
